### ISSUE TITLE
having trouble with the parser

### ISSUE THREAD

**Issue by IRigoutsos** [mato1092/runtastic-activity-lib#1]
Dear Matthias, 

Greetings. Thank you for making the parser available - I too am in the process of moving away from Runtastic ecosystem.

I was able to download and compile your parser without a problem.  When I run it, it does create gpx files but they are empty (i.e. they all have the basic 1K template and maybe the year e.g. 2018, or the latitude and that is pretty much it).   

Here is the error message that I get: 
===> Start parse Runtastic json to gpx files...
java.text.ParseException: Unparseable date: ""
        at java.base/java.text.DateFormat.parse(DateFormat.java:395)
        at Parser.convertTime(Parser.java:135)
        at Parser.parseJsonToGPX(Parser.java:101)
        at Parser.main(Parser.java:48)
Parsed 1 waypoints  from: 00137109-08c9-4186-b76d-e3628eb20d30.json successfully. GPX File is stored at: /Users/XXXX/output
java.text.ParseException: Unparseable date: ""
        at java.base/java.text.DateFormat.parse(DateFormat.java:395)
        at Parser.convertTime(Parser.java:135)
        at Parser.parseJsonToGPX(Parser.java:101)
        at Parser.main(Parser.java:48)
Parsed 1 waypoints  from: 00b9be87-0cd0-43c5-8451-bc4083545393.json successfully. GPX File is stored at: /Users/XXXX/output
…
and is the same message for all the files I attempted to convert.

Any and all help will be greatly appreciated!  Thank you,

Isidore

ps.  I have no idea what the difference is between the TCX and the GPX formats.  Would it be too complicate to create a parser that would turn Runtastic's JSON files to TCX files?

**Comment by mato1092** [comment]
Hi Isidore, 

I take a look into the project. I think runtastic changes the folder structure of the export directory. 
Maybe all the activity files are now in a subfolder of the 'Sport-sessions' directory. 
Please can you try,  to start the parser with the following line:
```java -jar runtastic-activity-parser /User/bob/Sport-sessions/GPS-data /User/bob/output```

Please let me know if this work for you. Then I will update the README.

Matthias

ps. I'am not an expert of the geospatial formats like TCX or GPX but i will take a look on the TCX format in next days. Maybe this is not too complicate. Then I can integrate this functionality soon. 
May I ask, what you want to do with the files?

**Comment by IRigoutsos** [comment]
Hi Matthias. 
Thank you for the speedy reply.  I ran the above variation and it now produces .gpx files but for some reason the longitude is not being read and thus is empty in the output file. Here is an example: 

{"version":1,"timestamp":"2017-04-20 23:45:26 +0200","longitude":-73.92963409423828,"latitude":40.767127990722656,"altitude":5.0,"accuracy_v":0,"accuracy_h":0,"speed":0.0,"duration":0,"distance":0,"elevation_gain":0,"elevation_loss":0}

becomes

<trkpt lon="" lat="40.767127990722656">
        <ele>5.0</ele>
        <time>2017-04-20T17:45:26.000Z</time>
      </trkpt>

Happy to try other things to help you get to the bottom of this. 

What do I want to do with the files?  Well, first I want to take them away from the grip of Runtastic. Their app is becoming overbearing in my opinion and I wanted to get the data out while I can. Then there is the issue of privacy.  A few days ago, I discovered iSmoothRun and a couple of runs later, I am convinced that it is a less intrusive and far more open app.  You can bulk import/export via dropbox which means the data is yours to keep. 

Thanks again, 
Isidore

**Comment by mato1092** [comment]
Hi Isidore, 

I took a second look at the project and found the bug. The implementation ignored negative longitude and latitude values.
I fixed this bug and hopefully it works now.

**Comment by IRigoutsos** [comment]
This fix seems to have done the trick. Thank you!

BTW, you may want to change the README file to indicate that the correct way to call the parser is to point to the GPS subdirectory of the Sessions directory. 

Thanks again,
Isidore

**Comment by mato1092** [comment]
I changed the README.md. The file is up to date now.

**Comment by IRigoutsos** [comment]
👍
Thank you!

**Comment by ZARuslan** [comment]
Hi! Sorry for my bad English. I'am not a coder/programmer and i don't know how to use source code. I understand, that i must compile project and then run it induer specific language_executor or how its correct name (i worked in university only with Pascal).
 I have exported my data from runtastic, So i need to convert it to regular gpx. I can send my export files in jar format. Can someone please convert them and send me back in gpx format? ZRuslan2006@gmail.com
Thanks!
